# Generated by Django 4.2.26 on 2025-11-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placas",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de placas"
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                ("anio", models.IntegerField(verbose_name="Año de fabricación")),
                (
                    "capacidad",
                    models.IntegerField(verbose_name="Capacidad de pasajeros"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Mantenimiento", "Mantenimiento"),
                            ("En Viaje", "En Viaje"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Camión",
                "verbose_name_plural": "Camiones",
            },
        ),
        migrations.CreateModel(
            name="Chofer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre completo"),
                ),
                (
                    "licencia",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de licencia"
                    ),
                ),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="Disponible", max_length=20)),
            ],
            options={
                "verbose_name": "Chófer",
                "verbose_name_plural": "Choferes",
            },
        ),
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField()),
                (
                    "camion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenimientos",
                        to="flota.camion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
            },
        ),
    ]
