# Generated by Django 4.2.26 on 2025-11-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=100, unique=True)),
                ("direccion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="SocioNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        max_length=150, verbose_name="Nombre o Razón Social"
                    ),
                ),
                (
                    "contacto",
                    models.CharField(
                        max_length=100, verbose_name="Persona de contacto"
                    ),
                ),
                ("telefono", models.CharField(max_length=20)),
                (
                    "correo",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="Correo del socio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Socio de Negocio",
                "verbose_name_plural": "Socios de Negocio",
            },
        ),
    ]
