# Generated by Django 4.2.26 on 2025-11-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contactos", "0001_initial"),
        ("flota", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Viaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destino", models.CharField(max_length=200)),
                ("fecha_salida", models.DateTimeField()),
                ("fecha_regreso", models.DateTimeField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Reservado", "Reservado"),
                            ("Confirmado", "Confirmado"),
                            ("Realizado", "Realizado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Reservado",
                        max_length=20,
                    ),
                ),
                (
                    "camion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes_operaciones",
                        to="flota.camion",
                    ),
                ),
                (
                    "chofer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes_operaciones",
                        to="flota.chofer",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes_operaciones",
                        to="contactos.cliente",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viajes_enviados",
                        to="contactos.socionegocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viaje",
                "verbose_name_plural": "Viajes",
            },
        ),
    ]
